const SECRET = process.env.SECRET;
const SESSION_SECRET = process.env.SESSION_SECRET;

const MAIL_CONFIG = require("./mail");

const URL_BACKOFFICE_FRONTEND = process.env.URL_BACKOFFICE_FRONTEND || ("https://" + process.env.WEBSITE_HOSTNAME);

const SUPERADMIN_INITIAL_PASSWORD = process.env.SUPERADMIN_INITIAL_PASSWORD;

module.exports = {
  MAIL_CONFIG,
  SECRET,
  SESSION_SECRET,
  URL_BACKOFFICE_FRONTEND,
  SUPERADMIN_INITIAL_PASSWORD,
};
